redmine/redmine-3.4.6/config/routes.rb
# Redmine - project management software
# Copyright (C) 2006-2017  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

Rails.application.routes.draw do
  root :to => 'welcome#index', :as => 'home'

  match 'login', :to => 'account#login', :as => 'signin', :via => [:get, :post]
  match 'logout', :to => 'account#logout', :as => 'signout', :via => [:get, :post]
  match 'account/register', :to => 'account#register', :via => [:get, :post], :as => 'register'
  match 'account/lost_password', :to => 'account#lost_password', :via => [:get, :post], :as => 'lost_password'
  match 'account/activate', :to => 'account#activate', :via => :get
  get 'account/activation_email', :to => 'account#activation_email', :as => 'activation_email'

  match '/news/preview', :controller => 'previews', :action => 'news', :as => 'preview_news', :via => [:get, :post, :put, :patch]
  match '/issues/preview/new/:project_id', :to => 'previews#issue', :as => 'preview_new_issue', :via => [:get, :post, :put, :patch]
  match '/issues/preview/edit/:id', :to => 'previews#issue', :as => 'preview_edit_issue', :via => [:get, :post, :put, :patch]
  match '/issues/preview', :to => 'previews#issue', :as => 'preview_issue', :via => [:get, :post, :put, :patch]

  match 'projects/:id/wiki', :to => 'wikis#edit', :via => :post
  match 'projects/:id/wiki/destroy', :to => 'wikis#destroy', :via => [:get, :post]

  match 'boards/:board_id/topics/new', :to => 'messages#new', :via => [:get, :post], :as => 'new_board_message'
  get 'boards/:board_id/topics/:id', :to => 'messages#show', :as => 'board_message'
  match 'boards/:board_id/topics/quote/:id', :to => 'messages#quote', :via => [:get, :post]
  get 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'

  post 'boards/:board_id/topics/preview', :to => 'messages#preview', :as => 'preview_board_message'
  post 'boards/:board_id/topics/:id/replies', :to => 'messages#reply'
  post 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'
  post 'boards/:board_id/topics/:id/destroy', :to => 'messages#destroy'

  # Misc issue routes. TODO: move into resources
  match '/issues/auto_complete', :to => 'auto_completes#issues', :via => :get, :as => 'auto_complete_issues'
  match '/issues/context_menu', :to => 'context_menus#issues', :as => 'issues_context_menu', :via => [:get, :post]
  match '/issues/changes', :to => 'journals#index', :as => 'issue_changes', :via => :get
  match '/issues/:id/quoted', :to => 'journals#new', :id => /\d+/, :via => :post, :as => 'quoted_issue'

  resources :journals, :only => [:edit, :update] do
    member do
      get 'diff'
    end
  end

  get '/projects/:project_id/issues/gantt', :to => 'gantts#show', :as => 'project_gantt'
  get '/issues/gantt', :to => 'gantts#show'

  get '/projects/:project_id/issues/calendar', :to => 'calendars#show', :as => 'project_calendar'
  get '/issues/calendar', :to => 'calendars#show'

  get 'projects/:id/issues/report', :to => 'reports#issue_report', :as => 'project_issues_report'
  get 'projects/:id/issues/report/:detail', :to => 'reports#issue_report_details', :as => 'project_issues_report_details'

  get   '/issues/imports/new', :to => 'imports#new', :as => 'new_issues_import'
  post  '/imports', :to => 'imports#create', :as => 'imports'
  get   '/imports/:id', :to => 'imports#show', :as => 'import'
  match '/imports/:id/settings', :to => 'imports#settings', :via => [:get, :post], :as => 'import_settings'
  match '/imports/:id/mapping', :to => 'imports#mapping', :via => [:get, :post], :as => 'import_mapping'
  match '/imports/:id/run', :to => 'imports#run', :via => [:get, :post], :as => 'import_run'

  match 'my/account', :controller => 'my', :action => 'account', :via => [:get, :post]
  match 'my/account/destroy', :controller => 'my', :action => 'destroy', :via => [:get, :post]
  match 'my/page', :controller => 'my', :action => 'page', :via => :get
  post 'my/page', :to => 'my#update_page'
  match 'my', :controller => 'my', :action => 'index', :via => :get # Redirects to my/page
  get 'my/api_key', :to => 'my#show_api_key', :as => 'my_api_key'
  post 'my/api_key', :to => 'my#reset_api_key'
  post 'my/rss_key', :to => 'my#reset_rss_key', :as => 'my_rss_key'
  match 'my/password', :controller => 'my', :action => 'password', :via => [:get, :post]
  match 'my/add_block', :controller => 'my', :action => 'add_block', :via => :post
  match 'my/remove_block', :controller => 'my', :action => 'remove_block', :via => :post
  match 'my/order_blocks', :controller => 'my', :action => 'order_blocks', :via => :post

  resources :users do
    resources :memberships, :controller => 'principal_memberships'
    resources :email_addresses, :only => [:index, :create, :update, :destroy]
  end

  post 'watchers/watch', :to => 'watchers#watch', :as => 'watch'
  delete 'watchers/watch', :to => 'watchers#unwatch'
  get 'watchers/new', :to => 'watchers#new', :as => 'new_watchers'
  post 'watchers', :to => 'watchers#create'
  post 'watchers/append', :to => 'watchers#append'
  delete 'watchers', :to => 'watchers#destroy'
  get 'watchers/autocomplete_for_user', :to => 'watchers#autocomplete_for_user'
  # Specific routes for issue watchers API
  post 'issues/:object_id/watchers', :to => 'watchers#create', :object_type => 'issue'
  delete 'issues/:object_id/watchers/:user_id' => 'watchers#destroy', :object_type => 'issue'

  resources :projects do
    collection do
      get 'autocomplete'
    end

    member do
      get 'settings(/:tab)', :action => 'settings', :as => 'settings'
      post 'modules'
      post 'archive'
      post 'unarchive'
      post 'close'
      post 'reopen'
      match 'copy', :via => [:get, :post]
    end

    shallow do
      resources :memberships, :controller => 'members' do
        collection do
          get 'autocomplete'
        end
      end
    end

    resource :enumerations, :controller => 'project_enumerations', :only => [:update, :destroy]

    get 'issues/:copy_from/copy', :to => 'issues#new', :as => 'copy_issue'
    resources :issues, :only => [:index, :new, :create]
    # Used when updating the form of a new issue
    post 'issues/new', :to => 'issues#new'

    resources :files, :only => [:index, :new, :create]

    resources :versions, :except => [:index, :show, :edit, :update, :destroy] do
      collection do
        put 'close_completed'
      end
    end
    get 'versions.:format', :to => 'versions#index'
    get 'roadmap', :to => 'versions#index', :format => false
    get 'versions', :to => 'versions#index'

    resources :news, :except => [:show, :edit, :update, :destroy]
    resources :time_entries, :controller => 'timelog', :except => [:show, :edit, :update, :destroy] do
      get 'report', :on => :collection
    end
    resources :queries, :only => [:new, :create]
    shallow do
      resources :issue_categories
    end
    resources :documents, :except => [:show, :edit, :update, :destroy]
    resources :boards
    shallow do
      resources :repositories, :except => [:index, :show] do
        member do
          match 'committers', :via => [:get, :post]
        end
      end
    end
  
    match 'wiki/index', :controller => 'wiki', :action => 'index', :via => :get
    resources :wiki, :except => [:index, :create], :as => 'wiki_page' do
      member do
        get 'rename'
        post 'rename'
        get 'history'
        get 'diff'
        match 'preview', :via => [:post, :put, :patch]
        post 'protect'
        post 'add_attachment'
      end
      collection do
        get 'export'
        get 'date_index'
        post 'new'
      end
    end
    match 'wiki', :controller => 'wiki', :action => 'show', :via => :get
    get 'wiki/:id/:version', :to => 'wiki#show', :constraints => {:version => /\d+/}
    delete 'wiki/:id/:version', :to => 'wiki#destroy_version'
    get 'wiki/:id/:version/annotate', :to => 'wiki#annotate'
    get 'wiki/:id/:version/diff', :to => 'wiki#diff'
  end

  resources :issues do
    member do
      # Used when updating the form of an existing issue
      patch 'edit', :to => 'issues#edit'
    end
    collection do
      match 'bulk_edit', :via => [:get, :post]
      post 'bulk_update'
    end
    resources :time_entries, :controller => 'timelog', :only => [:new, :create]
    shallow do
      resources :relations, :controller => 'issue_relations', :only => [:index, :show, :create, :destroy]
    end
  end
  # Used when updating the form of a new issue outside a project
  post '/issues/new', :to => 'issues#new'
  match '/issues', :controller => 'issues', :action => 'destroy', :via => :delete

  resources :queries, :except => [:show]
  get '/queries/filter', :to => 'queries#filter', :as => 'queries_filter'

  resources :news, :only => [:index, :show, :edit, :update, :destroy]
  match '/news/:id/comments', :to => 'comments#create', :via => :post
  match '/news/:id/comments/:comment_id', :to => 'comments#destroy', :via => :delete

  resources :versions, :only => [:show, :edit, :update, :destroy] do
    post 'status_by', :on => :member
  end

  resources :documents, :only => [:show, :edit, :update, :destroy] do
    post 'add_attachment', :on => :member
  end

  match '/time_entries/context_menu', :to => 'context_menus#time_entries', :as => :time_entries_context_menu, :via => [:get, :post]

redmine/redmine-3.4.6/app/controllers/gantts_controller.rb
# Redmine - project management software
# Copyright (C) 2006-2017  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class GanttsController < ApplicationController
  menu_item :gantt
  before_action :find_optional_project

  rescue_from Query::StatementInvalid, :with => :query_statement_invalid

  helper :gantt
  helper :issues
  helper :projects
  helper :queries
  include QueriesHelper
  include Redmine::Export::PDF

  def show
    @gantt = Redmine::Helpers::Gantt.new(params)
    @gantt.project = @project
    retrieve_query
    @query.group_by = nil
    @gantt.query = @query if @query.valid?

    basename = (@project ? "#{@project.identifier}-" : '') + 'gantt'

    respond_to do |format|
      format.html { render :action => "show", :layout => !request.xhr? }
      format.png  { send_data(@gantt.to_image, :disposition => 'inline', :type => 'image/png', :filename => "#{basename}.png") } if @gantt.respond_to?('to_image')
      format.pdf  { send_data(@gantt.to_pdf, :type => 'application/pdf', :filename => "#{basename}.pdf") }
    end
  end
end

redmine/redmine-3.4.6/app/helpers/gantt_helper.rb
# encoding: utf-8
#
# Redmine - project management software
# Copyright (C) 2006-2017  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

module GanttHelper

  def gantt_zoom_link(gantt, in_or_out)
    case in_or_out
    when :in
      if gantt.zoom < 4
        link_to l(:text_zoom_in),
          {:params => request.query_parameters.merge(gantt.params.merge(:zoom => (gantt.zoom + 1)))},
          :class => 'icon icon-zoom-in'
      else
        content_tag(:span, l(:text_zoom_in), :class => 'icon icon-zoom-in').html_safe
      end

    when :out
      if gantt.zoom > 1
        link_to l(:text_zoom_out),
          {:params => request.query_parameters.merge(gantt.params.merge(:zoom => (gantt.zoom - 1)))},
          :class => 'icon icon-zoom-out'
      else
        content_tag(:span, l(:text_zoom_out), :class => 'icon icon-zoom-out').html_safe
      end
    end
  end
end

redmine/redmine-3.4.6/app/views/gantts/show.html.erb
<% @gantt.view = self %>
<div class="contextual">
<% if !@query.new_record? && @query.editable_by?(User.current) %>
  <%= link_to l(:button_edit), edit_query_path(@query, :gantt => 1), :class => 'icon icon-edit' %>
  <%= delete_link query_path(@query, :gantt => 1) %>
<% end %>
</div>

<h2><%= @query.new_record? ? l(:label_gantt) : @query.name %></h2>

<%= form_tag({:controller => 'gantts', :action => 'show',
             :project_id => @project, :month => params[:month],
             :year => params[:year], :months => params[:months]},
             :method => :get, :id => 'query_form') do %>
<%= hidden_field_tag 'set_filter', '1' %>
<%= hidden_field_tag 'gantt', '1' %>
<fieldset id="filters" class="collapsible <%= @query.new_record? ? "" : "collapsed" %>">
  <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
  <div style="<%= @query.new_record? ? "" : "display: none;" %>">
    <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
  </div>
</fieldset>
<fieldset id="options" class="collapsible collapsed">
  <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
  <div style="display: none;">
    <table>
      <tr>
        <td>
          <fieldset>
            <legend><%= l(:label_related_issues) %></legend>
            <label for="draw_relations">
              <%= check_box 'query', 'draw_relations', :id => 'draw_relations' %>
              <% rels = [IssueRelation::TYPE_BLOCKS, IssueRelation::TYPE_PRECEDES] %>
              <% rels.each do |rel| %>
                <% color = Redmine::Helpers::Gantt::DRAW_TYPES[rel][:color] %>
                <%= content_tag(:span, '&nbsp;&nbsp;&nbsp;'.html_safe,
                                :style => "background-color: #{color}") %>
                <%= l(IssueRelation::TYPES[rel][:name]) %>
              <% end %>
            </label>
          </fieldset>
        </td>
        <td>
          <fieldset>
            <legend><%= l(:label_gantt_progress_line) %></legend>
            <label for="draw_progress_line">
              <%= check_box 'query', 'draw_progress_line', :id => 'draw_progress_line' %>
              <%= l(:label_display) %>
            </label>
          </fieldset>
        </td>
      </tr>
    </table>
  </div>
</fieldset>

<p class="contextual">
  <%= gantt_zoom_link(@gantt, :in) %>
  <%= gantt_zoom_link(@gantt, :out) %>
</p>

<p class="buttons">
<%= text_field_tag 'months', @gantt.months, :size => 2 %>
<%= l(:label_months_from) %>
<%= select_month(@gantt.month_from, :prefix => "month", :discard_type => true) %>
<%= select_year(@gantt.year_from, :prefix => "year", :discard_type => true) %>
<%= hidden_field_tag 'zoom', @gantt.zoom %>

<%= link_to_function l(:button_apply), '$("#query_form").submit()',
                     :class => 'icon icon-checked' %>
<%= link_to l(:button_clear), { :project_id => @project, :set_filter => 1 },
            :class => 'icon icon-reload' %>
<% if @query.new_record? && User.current.allowed_to?(:save_queries, @project, :global => true) %>
  <%= link_to_function l(:button_save),
                       "$('#query_form').attr('action', '#{ @project ? new_project_query_path(@project) : new_query_path }').submit();",
                       :class => 'icon icon-save' %>
<% end %>
</p>
<% end %>

<%= error_messages_for 'query' %>
<% if @query.valid? %>
<%
  zoom = 1
  @gantt.zoom.times { zoom = zoom * 2 }

  subject_width = 330
  header_height = 18

  headers_height = header_height
  show_weeks = false
  show_days  = false
  show_day_num = false

  if @gantt.zoom > 1
    show_weeks = true
    headers_height = 2 * header_height
    if @gantt.zoom > 2
        show_days = true
        headers_height = 3 * header_height
        if @gantt.zoom > 3
          show_day_num = true
          headers_height = 4 * header_height
        end
    end
  end

  # Width of the entire chart
  g_width = ((@gantt.date_to - @gantt.date_from + 1) * zoom).to_i
  @gantt.render(:top => headers_height + 8,
                :zoom => zoom,
                :g_width => g_width,
                :subject_width => subject_width)
  g_height = [(20 * (@gantt.number_of_rows + 6)) + 150, 206].max
  t_height = g_height + headers_height
%>

<% if @gantt.truncated %>
  <p class="warning"><%= l(:notice_gantt_chart_truncated, :max => @gantt.max_rows) %></p>
<% end %>

<table style="width:100%; border:0; border-collapse: collapse;">
<tr>
<td style="width:<%= subject_width %>px; padding:0px;" class="gantt_subjects_column">
  <%
    style  = ""
    style += "position:relative;"
    style += "height: #{t_height + 24}px;"
    style += "width: #{subject_width + 1}px;"
  %>
  <%= content_tag(:div, :style => style, :class => "gantt_subjects_container") do %>
    <%
      style  = ""
      style += "right:-2px;"
      style += "width: #{subject_width}px;"
      style += "height: #{headers_height}px;"
      style += 'background: #eee;'
    %>
    <%= content_tag(:div, "", :style => style, :class => "gantt_hdr") %>
    <%
      style  = ""
      style += "right:-2px;"
      style += "width: #{subject_width}px;"
      style += "height: #{t_height}px;"
      style += 'border-left: 1px solid #c0c0c0;'
      style += 'overflow: hidden;'
    %>
    <%= content_tag(:div, "", :style => style, :class => "gantt_hdr") %>
    <%= content_tag(:div, :class => "gantt_subjects") do %>
      <%= @gantt.subjects.html_safe %>
    <% end %>
  <% end %>
</td>

<td>
<div style="position:relative;height:<%= t_height + 24 %>px;overflow:auto;" id="gantt_area">
<%
  style  = ""
  style += "width: #{g_width - 1}px;"
  style += "height: #{headers_height}px;"
  style += 'background: #eee;'
%>
<%= content_tag(:div, '&nbsp;'.html_safe, :style => style, :class => "gantt_hdr") %>

<% ###### Months headers ###### %>
<%
  month_f = @gantt.date_from
  left = 0
  height = (show_weeks ? header_height : header_height + g_height)
%>
<% @gantt.months.times do %>
  <%
    width = (((month_f >> 1) - month_f) * zoom - 1).to_i
    style  = ""
    style += "left: #{left}px;"
    style += "width: #{width}px;"
    style += "height: #{height}px;"
  %>
  <%= content_tag(:div, :style => style, :class => "gantt_hdr") do %>
    <%= link_to "#{month_f.year}-#{month_f.month}",
                @gantt.params.merge(:year => month_f.year, :month => month_f.month),
                :title => "#{month_name(month_f.month)} #{month_f.year}" %>
  <% end %>
  <%
    left = left + width + 1
    month_f = month_f >> 1
  %>
<% end %>

<% ###### Weeks headers ###### %>
<% if show_weeks %>
  <%
    left = 0
    height = (show_days ? header_height - 1 : header_height - 1 + g_height)
  %>
  <% if @gantt.date_from.cwday == 1 %>
    <%
      # @date_from is monday
      week_f = @gantt.date_from
    %>
  <% else %>
    <%
      # find next monday after @date_from
      week_f = @gantt.date_from + (7 - @gantt.date_from.cwday + 1)
      width = (7 - @gantt.date_from.cwday + 1) * zoom - 1
      style  = ""
      style += "left: #{left}px;"
      style += "top: 19px;"
      style += "width: #{width}px;"
      style += "height: #{height}px;"
    %>
    <%= content_tag(:div, '&nbsp;'.html_safe,
                    :style => style, :class => "gantt_hdr") %>
    <% left = left + width + 1 %>
  <% end %>
  <% while week_f <= @gantt.date_to %>
    <%
      width = ((week_f + 6 <= @gantt.date_to) ?
                  7 * zoom - 1 :
                  (@gantt.date_to - week_f + 1) * zoom - 1).to_i
      style  = ""
      style += "left: #{left}px;"
      style += "top: 19px;"
      style += "width: #{width}px;"
      style += "height: #{height}px;"
    %>
    <%= content_tag(:div, :style => style, :class => "gantt_hdr") do %>
      <%= content_tag(:small) do %>
        <%= week_f.cweek if width >= 16 %>
      <% end %>
    <% end %>
    <%
      left = left + width + 1
      week_f = week_f + 7
    %>
  <% end %>
<% end %>

<% ###### Day numbers headers ###### %>
<% if show_day_num %>
  <%
    left = 0
    height = g_height + header_height*2 - 1
    wday = @gantt.date_from.cwday
    day_num = @gantt.date_from
  %>
  <% (@gantt.date_to - @gantt.date_from + 1).to_i.times do %>
    <%
      width =  zoom - 1
      style = ""
      style += "left:#{left}px;"
      style += "top:37px;"
      style += "width:#{width}px;"
      style += "height:#{height}px;"
      style += "font-size:0.7em;"
      clss = "gantt_hdr"
      clss << " nwday" if @gantt.non_working_week_days.include?(wday)
    %>
    <%= content_tag(:div, :style => style, :class => clss) do %>
      <%= day_num.day %>
    <% end %>
    <%
     left = left + width+1
     day_num = day_num + 1
     wday = wday + 1
     wday = 1 if wday > 7
    %>
  <% end %>
<% end %> 

<% ###### Days headers ####### %>
<% if show_days %>
  <%
    left = 0
    height = g_height + header_height - 1
    top = (show_day_num ? 55 : 37)
    wday = @gantt.date_from.cwday
  %>
  <% (@gantt.date_to - @gantt.date_from + 1).to_i.times do %>
    <%
      width =  zoom - 1
      style  = ""
      style += "left: #{left}px;"
      style += "top: #{top}px;"
      style += "width: #{width}px;"
      style += "height: #{height}px;"
      style += "font-size:0.7em;"
      clss = "gantt_hdr"
      clss << " nwday" if @gantt.non_working_week_days.include?(wday)
    %>
    <%= content_tag(:div, :style => style, :class => clss) do %>
      <%= day_letter(wday) %>
    <% end %>
    <%
      left = left + width + 1
      wday = wday + 1
      wday = 1 if wday > 7
    %>
  <% end %>
<% end %>

<%= @gantt.lines.html_safe %>

<% ###### Today red line (excluded from cache) ###### %>
<% if User.current.today >= @gantt.date_from and User.current.today <= @gantt.date_to %>
  <%
    today_left = (((User.current.today - @gantt.date_from + 1) * zoom).floor() - 1).to_i
    style  = ""
    style += "position: absolute;"
    style += "height: #{g_height}px;"
    style += "top: #{headers_height + 1}px;"
    style += "left: #{today_left}px;"
    style += "width:10px;"
    style += "border-left: 1px dashed red;"
  %>
  <%= content_tag(:div, '&nbsp;'.html_safe, :style => style, :id => 'today_line') %>
<% end %>
<%
  style  = ""
  style += "position: absolute;"
  style += "height: #{g_height}px;"
  style += "top: #{headers_height + 1}px;"
  style += "left: 0px;"
  style += "width: #{g_width - 1}px;"
%>
<%= content_tag(:div, '', :style => style, :id => "gantt_draw_area") %>
</div>
</td>
</tr>
</table>

<table style="width:100%">
<tr>
  <td style="text-align:left;">
    <%= link_to("\xc2\xab " + l(:label_previous),
                               {:params => request.query_parameters.merge(@gantt.params_previous)},
                               :accesskey => accesskey(:previous)) %>
  </td>
  <td style="text-align:right;">
    <%= link_to(l(:label_next) + " \xc2\xbb",
                               {:params => request.query_parameters.merge(@gantt.params_next)},
                               :accesskey => accesskey(:next)) %>
  </td>
</tr>
</table>

<% other_formats_links do |f| %>
  <%= f.link_to_with_query_parameters 'PDF', @gantt.params %>
  <%= f.link_to_with_query_parameters('PNG', @gantt.params) if @gantt.respond_to?('to_image') %>
<% end %>
<% end # query.valid? %>

<% content_for :sidebar do %>
  <%= render :partial => 'issues/sidebar' %>
<% end %>

<% html_title(l(:label_gantt)) -%>

<% content_for :header_tags do %>
  <%= javascript_include_tag 'raphael' %>
  <%= javascript_include_tag 'gantt' %>
<% end %>

<%= javascript_tag do %>
  var issue_relation_type = <%= raw Redmine::Helpers::Gantt::DRAW_TYPES.to_json %>;
  $(document).ready(drawGanttHandler);
  $(window).resize(drawGanttHandler);
  $(function() {
    $("#draw_relations").change(drawGanttHandler);
    $("#draw_progress_line").change(drawGanttHandler);
  });
<% end %>