redmine/redmine-3.4.6/config/routes.rb
# Redmine - project management software
# Copyright (C) 2006-2017  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

Rails.application.routes.draw do
  root :to => 'welcome#index', :as => 'home'

  match 'login', :to => 'account#login', :as => 'signin', :via => [:get, :post]
  match 'logout', :to => 'account#logout', :as => 'signout', :via => [:get, :post]
  match 'account/register', :to => 'account#register', :via => [:get, :post], :as => 'register'
  match 'account/lost_password', :to => 'account#lost_password', :via => [:get, :post], :as => 'lost_password'
  match 'account/activate', :to => 'account#activate', :via => :get
  get 'account/activation_email', :to => 'account#activation_email', :as => 'activation_email'

  match '/news/preview', :controller => 'previews', :action => 'news', :as => 'preview_news', :via => [:get, :post, :put, :patch]
  match '/issues/preview/new/:project_id', :to => 'previews#issue', :as => 'preview_new_issue', :via => [:get, :post, :put, :patch]
  match '/issues/preview/edit/:id', :to => 'previews#issue', :as => 'preview_edit_issue', :via => [:get, :post, :put, :patch]
  match '/issues/preview', :to => 'previews#issue', :as => 'preview_issue', :via => [:get, :post, :put, :patch]

  match 'projects/:id/wiki', :to => 'wikis#edit', :via => :post
  match 'projects/:id/wiki/destroy', :to => 'wikis#destroy', :via => [:get, :post]

  match 'boards/:board_id/topics/new', :to => 'messages#new', :via => [:get, :post], :as => 'new_board_message'
  get 'boards/:board_id/topics/:id', :to => 'messages#show', :as => 'board_message'
  match 'boards/:board_id/topics/quote/:id', :to => 'messages#quote', :via => [:get, :post]
  get 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'

  post 'boards/:board_id/topics/preview', :to => 'messages#preview', :as => 'preview_board_message'
  post 'boards/:board_id/topics/:id/replies', :to => 'messages#reply'
  post 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'
  post 'boards/:board_id/topics/:id/destroy', :to => 'messages#destroy'

  # Misc issue routes. TODO: move into resources
  match '/issues/auto_complete', :to => 'auto_completes#issues', :via => :get, :as => 'auto_complete_issues'
  match '/issues/context_menu', :to => 'context_menus#issues', :as => 'issues_context_menu', :via => [:get, :post]
  match '/issues/changes', :to => 'journals#index', :as => 'issue_changes', :via => :get
  match '/issues/:id/quoted', :to => 'journals#new', :id => /\d+/, :via => :post, :as => 'quoted_issue'

  resources :journals, :only => [:edit, :update] do
    member do
      get 'diff'
    end
  end

  get '/projects/:project_id/issues/gantt', :to => 'gantts#show', :as => 'project_gantt'
  get '/issues/gantt', :to => 'gantts#show'

  get '/projects/:project_id/issues/calendar', :to => 'calendars#show', :as => 'project_calendar'
  get '/issues/calendar', :to => 'calendars#show'

  get 'projects/:id/issues/report', :to => 'reports#issue_report', :as => 'project_issues_report'
  get 'projects/:id/issues/report/:detail', :to => 'reports#issue_report_details', :as => 'project_issues_report_details'

  get   '/issues/imports/new', :to => 'imports#new', :as => 'new_issues_import'
  post  '/imports', :to => 'imports#create', :as => 'imports'
  get   '/imports/:id', :to => 'imports#show', :as => 'import'
  match '/imports/:id/settings', :to => 'imports#settings', :via => [:get, :post], :as => 'import_settings'
  match '/imports/:id/mapping', :to => 'imports#mapping', :via => [:get, :post], :as => 'import_mapping'
  match '/imports/:id/run', :to => 'imports#run', :via => [:get, :post], :as => 'import_run'

  match 'my/account', :controller => 'my', :action => 'account', :via => [:get, :post]
  match 'my/account/destroy', :controller => 'my', :action => 'destroy', :via => [:get, :post]
  match 'my/page', :controller => 'my', :action => 'page', :via => :get
  post 'my/page', :to => 'my#update_page'
  match 'my', :controller => 'my', :action => 'index', :via => :get # Redirects to my/page
  get 'my/api_key', :to => 'my#show_api_key', :as => 'my_api_key'
  post 'my/api_key', :to => 'my#reset_api_key'
  post 'my/rss_key', :to => 'my#reset_rss_key', :as => 'my_rss_key'
  match 'my/password', :controller => 'my', :action => 'password', :via => [:get, :post]
  match 'my/add_block', :controller => 'my', :action => 'add_block', :via => :post
  match 'my/remove_block', :controller => 'my', :action => 'remove_block', :via => :post
  match 'my/order_blocks', :controller => 'my', :action => 'order_blocks', :via => :post

  resources :users do
    resources :memberships, :controller => 'principal_memberships'
    resources :email_addresses, :only => [:index, :create, :update, :destroy]
  end

  post 'watchers/watch', :to => 'watchers#watch', :as => 'watch'
  delete 'watchers/watch', :to => 'watchers#unwatch'
  get 'watchers/new', :to => 'watchers#new', :as => 'new_watchers'
  post 'watchers', :to => 'watchers#create'
  post 'watchers/append', :to => 'watchers#append'
  delete 'watchers', :to => 'watchers#destroy'
  get 'watchers/autocomplete_for_user', :to => 'watchers#autocomplete_for_user'
  # Specific routes for issue watchers API
  post 'issues/:object_id/watchers', :to => 'watchers#create', :object_type => 'issue'
  delete 'issues/:object_id/watchers/:user_id' => 'watchers#destroy', :object_type => 'issue'

  resources :projects do
    collection do
      get 'autocomplete'
    end

    member do
      get 'settings(/:tab)', :action => 'settings', :as => 'settings'
      post 'modules'
      post 'archive'
      post 'unarchive'
      post 'close'
      post 'reopen'
      match 'copy', :via => [:get, :post]
    end

    shallow do
      resources :memberships, :controller => 'members' do
        collection do
          get 'autocomplete'
        end
      end
    end

    resource :enumerations, :controller => 'project_enumerations', :only => [:update, :destroy]

    get 'issues/:copy_from/copy', :to => 'issues#new', :as => 'copy_issue'
    resources :issues, :only => [:index, :new, :create]
    # Used when updating the form of a new issue
    post 'issues/new', :to => 'issues#new'

    resources :files, :only => [:index, :new, :create]

    resources :versions, :except => [:index, :show, :edit, :update, :destroy] do
      collection do
        put 'close_completed'
      end
    end
    get 'versions.:format', :to => 'versions#index'
    get 'roadmap', :to => 'versions#index', :format => false
    get 'versions', :to => 'versions#index'

    resources :news, :except => [:show, :edit, :update, :destroy]
    resources :time_entries, :controller => 'timelog', :except => [:show, :edit, :update, :destroy] do
      get 'report', :on => :collection
    end
    resources :queries, :only => [:new, :create]
    shallow do
      resources :issue_categories
    end
    resources :documents, :except => [:show, :edit, :update, :destroy]
    resources :boards
    shallow do
      resources :repositories, :except => [:index, :show] do
        member do
          match 'committers', :via => [:get, :post]
        end
      end
    end
  
    match 'wiki/index', :controller => 'wiki', :action => 'index', :via => :get
    resources :wiki, :except => [:index, :create], :as => 'wiki_page' do
      member do
        get 'rename'
        post 'rename'
        get 'history'
        get 'diff'
        match 'preview', :via => [:post, :put, :patch]
        post 'protect'
        post 'add_attachment'
      end
      collection do
        get 'export'
        get 'date_index'
        post 'new'
      end
    end
    match 'wiki', :controller => 'wiki', :action => 'show', :via => :get
    get 'wiki/:id/:version', :to => 'wiki#show', :constraints => {:version => /\d+/}
    delete 'wiki/:id/:version', :to => 'wiki#destroy_version'
    get 'wiki/:id/:version/annotate', :to => 'wiki#annotate'
    get 'wiki/:id/:version/diff', :to => 'wiki#diff'
  end

  resources :issues do
    member do
      # Used when updating the form of an existing issue
      patch 'edit', :to => 'issues#edit'
    end
    collection do
      match 'bulk_edit', :via => [:get, :post]
      post 'bulk_update'
    end
    resources :time_entries, :controller => 'timelog', :only => [:new, :create]
    shallow do
      resources :relations, :controller => 'issue_relations', :only => [:index, :show, :create, :destroy]
    end
  end
  # Used when updating the form of a new issue outside a project
  post '/issues/new', :to => 'issues#new'
  match '/issues', :controller => 'issues', :action => 'destroy', :via => :delete

  resources :queries, :except => [:show]
  get '/queries/filter', :to => 'queries#filter', :as => 'queries_filter'

  resources :news, :only => [:index, :show, :edit, :update, :destroy]
  match '/news/:id/comments', :to => 'comments#create', :via => :post
  match '/news/:id/comments/:comment_id', :to => 'comments#destroy', :via => :delete

  resources :versions, :only => [:show, :edit, :update, :destroy] do
    post 'status_by', :on => :member
  end

  resources :documents, :only => [:show, :edit, :update, :destroy] do
    post 'add_attachment', :on => :member
  end

  match '/time_entries/context_menu', :to => 'context_menus#time_entries', :as => :time_entries_context_menu, :via => [:get, :post]

redmine/redmine-3.4.6/app/helpers/versions_helper.rb
# encoding: utf-8
#
# Redmine - project management software
# Copyright (C) 2006-2017  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

module VersionsHelper

  def version_anchor(version)
    if @project == version.project
      anchor version.name
    else
      anchor "#{version.project.try(:identifier)}-#{version.name}"
    end
  end

  def version_filtered_issues_path(version, options = {})
    options = {:fixed_version_id => version, :set_filter => 1}.merge(options)
    project = case version.sharing
      when 'hierarchy', 'tree'
        if version.project && version.project.root.visible?
          version.project.root
        else
          version.project
        end
      when 'system'
        nil
      else
        version.project
    end

    if project
      project_issues_path(project, options)
    else
      issues_path(options)
    end
  end

  STATUS_BY_CRITERIAS = %w(tracker status priority author assigned_to category)

  def render_issue_status_by(version, criteria)
    criteria = 'tracker' unless STATUS_BY_CRITERIAS.include?(criteria)

    h = Hash.new {|k,v| k[v] = [0, 0]}
    begin
      # Total issue count
      version.fixed_issues.group(criteria).count.each {|c,s| h[c][0] = s}
      # Open issues count
      version.fixed_issues.open.group(criteria).count.each {|c,s| h[c][1] = s}
    rescue ActiveRecord::RecordNotFound
    # When grouping by an association, Rails throws this exception if there's no result (bug)
    end
    # Sort with nil keys in last position
    counts = h.keys.sort {|a,b| a.nil? ? 1 : (b.nil? ? -1 : a <=> b)}.collect {|k| {:group => k, :total => h[k][0], :open => h[k][1], :closed => (h[k][0] - h[k][1])}}
    max = counts.collect {|c| c[:total]}.max

    render :partial => 'issue_counts', :locals => {:version => version, :criteria => criteria, :counts => counts, :max => max}
  end

  def status_by_options_for_select(value)
    options_for_select(STATUS_BY_CRITERIAS.collect {|criteria| [l("field_#{criteria}".to_sym), criteria]}, value)
  end
end

redmine/redmine-3.4.6/app/views/versions/_form.html.erb
<%= back_url_hidden_field_tag %>
<%= error_messages_for 'version' %>

<div class="box tabular">
<p><%= f.text_field :name, :size => 60, :required => true %></p>
<p><%= f.text_field :description, :size => 60 %></p>
<% unless @version.new_record? %>
  <p><%= f.select :status, Version::VERSION_STATUSES.collect {|s| [l("version_status_#{s}"), s]} %></p>
<% end %>
<p><%= f.text_field :wiki_page_title, :label => :label_wiki_page, :size => 60, :disabled => @project.wiki.nil? %></p>
<p><%= f.date_field :effective_date, :size => 10 %><%= calendar_for('version_effective_date') %></p>
<p><%= f.select :sharing, @version.allowed_sharings.collect {|v| [format_version_sharing(v), v]} %></p>
<% if @version.new_record? %>
<p><%= f.check_box :default_project_version, :label => :field_default_version %></p>
<% end %>

<% @version.custom_field_values.each do |value| %>
  <p><%= custom_field_tag_with_label :version, value %></p>
<% end %>

</div>

redmine/redmine-3.4.6/app/views/versions/_issue_counts.html.erb
<%= form_tag({}, :id => "status_by_form") do -%>
<fieldset>
<legend>
<%= l(:label_issues_by,
       select_tag('status_by',
                   status_by_options_for_select(criteria),
                   :id => 'status_by_select',
                   :data => {:remote => true, :method => 'post', :url => status_by_version_path(version)})).html_safe %>
</legend>
<% if counts.empty? %>
    <p><em><%= l(:label_no_data) %></em></p>
<% else %>
    <table>
    <% counts.each do |count| %>
    <tr>
        <td style="width:130px; text-align:right;">
          <% if count[:group] -%>
            <%= link_to(count[:group], project_issues_path(version.project, :set_filter => 1, :status_id => '*', :fixed_version_id => version, "#{criteria}_id" => count[:group])) %>
          <% else -%>
            <%= link_to(l(:label_none), project_issues_path(version.project, :set_filter => 1, :status_id => '*', :fixed_version_id => version, "#{criteria}_id" => "!*")) %>
          <% end %>
        </td>
        <td style="width:240px;">
            <%= progress_bar((count[:closed].to_f / count[:total])*100,
                  :legend => "#{count[:closed]}/#{count[:total]}") %>
        </td>
    </tr>
    <% end %>
    </table>
<% end %>
</fieldset>
<% end %>

redmine/redmine-3.4.6/app/views/versions/_new_modal.html.erb
<h3 class="title"><%=l(:label_version_new)%></h3>

<%= labelled_form_for @version, :url => project_versions_path(@project), :remote => true do |f| %>
<%= render :partial => 'versions/form', :locals => { :f => f } %>
  <p class="buttons">
    <%= submit_tag l(:button_create), :name => nil %>
    <%= submit_tag l(:button_cancel), :name => nil, :onclick => "hideModal(this);", :type => 'button' %>
  </p>
<% end %>

redmine/redmine-3.4.6/app/views/versions/_overview.html.erb
<div class="version-overview">
<% if version.completed? %>
  <p><%= format_date(version.effective_date) %></p>
<% elsif version.effective_date %>
  <p><strong><%= due_date_distance_in_words(version.effective_date) %></strong> (<%= format_date(version.effective_date) %>)</p>
<% end %>

<p><%=h version.description %></p>
<% if version.custom_field_values.any? %>
<ul>
  <% render_custom_field_values(version) do |custom_field, formatted| %>
    <li><span class="label"><%= custom_field.name %>:</span> <%= formatted %></li>
  <% end %>
</ul>
<% end %>

<% if version.issues_count > 0 %>
    <%= progress_bar([version.closed_percent, version.completed_percent],
                     :titles =>
                       ["%s: %0.0f%%" % [l(:label_closed_issues_plural), version.closed_percent],
                        "%s: %0.0f%%" % [l(:field_done_ratio), version.completed_percent]],
                     :legend => ('%0.0f%%' % version.completed_percent)) %>
    <p class="progress-info">
      <%= link_to(l(:label_x_issues, :count => version.issues_count),
                  version_filtered_issues_path(version, :status_id => '*')) %>
      &nbsp;
      (<%= link_to_if(version.closed_issues_count > 0,
                      l(:label_x_closed_issues_abbr, :count => version.closed_issues_count),
                      version_filtered_issues_path(version, :status_id => 'c')) %>
      &#8212;
      <%= link_to_if(version.open_issues_count > 0,
                     l(:label_x_open_issues_abbr, :count => version.open_issues_count),
                     version_filtered_issues_path(version, :status_id => 'o')) %>)
    </p>
<% else %>
    <p class="progress-info"><%= l(:label_roadmap_no_issues) %></p>
<% end %>
</div>

redmine/redmine-3.4.6/app/views/versions/create.js.erb
hideModal();
<% select = content_tag('select', content_tag('option') + version_options_for_select(@project.shared_versions.open, @version), :id => 'issue_fixed_version_id', :name => 'issue[fixed_version_id]') %>
$('#issue_fixed_version_id').replaceWith('<%= escape_javascript(select) %>');

redmine/redmine-3.4.6/app/views/versions/edit.html.erb
<h2><%=l(:label_version)%></h2>

<%= labelled_form_for @version, :html => {:multipart => true} do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_save) %>
<% end %>

redmine/redmine-3.4.6/app/views/versions/index.html.erb
<div class="contextual">
  <%= link_to(l(:label_version_new), new_project_version_path(@project),
              :class => 'icon icon-add') if User.current.allowed_to?(:manage_versions, @project) %>
</div>

<h2><%=l(:label_roadmap)%></h2>

<% if @versions.empty? %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
  <div id="roadmap">
  <% @versions.each do |version| %>
  <article class="version-article <%= version.css_classes %>">
    <% if User.current.allowed_to?(:manage_versions, version.project) %>
      <div class="contextual">
        <%= link_to l(:button_edit), edit_version_path(version), :title => l(:button_edit), :class => 'icon-only icon-edit' %>
      </div>
    <% end %>
    <header>
      <h3 class="icon icon-package version"><%= link_to_version version, :name => version_anchor(version) %></h3>
    </header>
    <%= render :partial => 'versions/overview', :locals => {:version => version} %>
    <%= render(:partial => "wiki/content",
               :locals => {:content => version.wiki_page.content}) if version.wiki_page %>
    <% if (issues = @issues_by_version[version]) && issues.size > 0 %>
      <%= form_tag({}, :data => {:cm_url => issues_context_menu_path}) do -%>
        <table class="list related-issues">
        <caption><%= l(:label_related_issues) %></caption>
        <% issues.each do |issue| -%>
          <tr class="hascontextmenu">
            <td class="checkbox"><%= check_box_tag 'ids[]', issue.id, false, :id => nil %></td>
            <td class="subject"><%= link_to_issue(issue, :project => (@project != issue.project)) %></td>
          </tr>
        <% end -%>
        </table>
      <% end %>
    <% end %>
    <%= call_hook :view_projects_roadmap_version_bottom, :version => version %>
  </article>
  <% end %>
  </div>
<% end %>

<% content_for :sidebar do %>
<%= form_tag({}, :method => :get) do %>
<h3><%= l(:label_roadmap) %></h3>
<ul>
<% @trackers.each do |tracker| %>
  <li>
    <label>
      <%= check_box_tag("tracker_ids[]", tracker.id,
                        (@selected_tracker_ids.include? tracker.id.to_s),
                        :id => nil) %>
      <%= tracker.name %>
    </label>
  </li>
<% end %>
</ul>
<p></p>
<ul>
  <li>
    <label for="completed">
      <%= check_box_tag "completed", 1, params[:completed] %> <%= l(:label_show_completed_versions) %>
    </label>
  </li>
  <% if @project.descendants.active.any? %>
  <li>
    <%= hidden_field_tag 'with_subprojects', 0, :id => nil %>
    <label>
      <%= check_box_tag 'with_subprojects', 1, @with_subprojects %> <%=l(:label_subproject_plural)%>
    </label>
  </li>
  <% end %>
</ul>
<p><%= submit_tag l(:button_apply), :class => 'button-small', :name => nil %></p>
<% end %>

<h3><%= l(:label_version_plural) %></h3>
<ul>
<% @versions.each do |version| %>
  <li>
    <%= link_to(format_version_name(version), "##{version_anchor(version)}") %>
  </li>
<% end %>
</ul>
<% if @completed_versions.present? %>
<p>
  <%= link_to_function l(:label_completed_versions),
                       '$("#toggle-completed-versions").toggleClass("collapsed"); $("#completed-versions").toggle()',
                       :id => 'toggle-completed-versions', :class => 'collapsible collapsed' %>
  <ul id = "completed-versions" style = "display:none;">
    <% @completed_versions.each do |version| %>
      <li><%= link_to_version version %></li>
    <% end %>
  </ul>
</p>
<% end %>
<% end %>

<% html_title(l(:label_roadmap)) %>

<%= context_menu %>

redmine/redmine-3.4.6/app/views/versions/new.html.erb
<h2><%=l(:label_version_new)%></h2>

<%= labelled_form_for @version, :url => project_versions_path(@project), :html => {:multipart => true} do |f| %>
<%= render :partial => 'versions/form', :locals => { :f => f } %>
<%= submit_tag l(:button_create) %>
<% end %>

redmine/redmine-3.4.6/app/views/versions/new.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'versions/new_modal') %>');
showModal('ajax-modal', '600px');

redmine/redmine-3.4.6/app/views/versions/show.html.erb
<div class="contextual">
<%= link_to(l(:button_edit), edit_version_path(@version), :class => 'icon icon-edit') if User.current.allowed_to?(:manage_versions, @version.project) %>
<%= link_to_if_authorized(l(:button_edit_associated_wikipage, :page_title => @version.wiki_page_title), {:controller => 'wiki', :action => 'edit', :project_id => @version.project, :id => Wiki.titleize(@version.wiki_page_title)}, :class => 'icon icon-edit') unless @version.wiki_page_title.blank? || @version.project.wiki.nil? %>
<%= delete_link version_path(@version, :back_url => url_for(:controller => 'versions', :action => 'index', :project_id => @version.project)) if User.current.allowed_to?(:manage_versions, @version.project) %>
<%= call_hook(:view_versions_show_contextual, { :version => @version, :project => @project }) %>
</div>

<h2><%= @version.name %></h2>

<div id="roadmap" class="<%= @version.css_classes %>">
<%= render :partial => 'versions/overview', :locals => {:version => @version} %>
<%= render(:partial => "wiki/content", :locals => {:content => @version.wiki_page.content}) if @version.wiki_page %>

<div id="version-summary">
<% if @version.estimated_hours > 0 || User.current.allowed_to?(:view_time_entries, @project) %>
<fieldset class="time-tracking"><legend><%= l(:label_time_tracking) %></legend>
<table>
<tr>
    <th><%= l(:field_estimated_hours) %></th>
    <td class="total-hours"><%= link_to html_hours(l_hours(@version.estimated_hours)),
                                        project_issues_path(@version.project, :set_filter => 1, :status_id => '*', :fixed_version_id => @version.id, :c => [:tracker, :status, :subject, :estimated_hours], :t => [:estimated_hours]) %></td>
</tr>
<% if User.current.allowed_to_view_all_time_entries?(@project) %>
<tr>
    <th><%= l(:label_spent_time) %></th>
    <td class="total-hours"><%= link_to html_hours(l_hours(@version.spent_hours)),
                                        project_time_entries_path(@version.project, :set_filter => 1, :"issue.fixed_version_id" => @version.id) %></td>
</tr>
<% end %>
</table>
</fieldset>
<% end %>

<div id="status_by">
<%= render_issue_status_by(@version, params[:status_by]) if @version.fixed_issues.exists? %>
</div>
</div>

<% if @issues.present? %>
<%= form_tag({}, :data => {:cm_url => issues_context_menu_path}) do -%>
  <table class="list related-issues">
  <caption><%= l(:label_related_issues) %></caption>
  <%- @issues.each do |issue| -%>
    <tr class="issue hascontextmenu">
      <td class="checkbox"><%= check_box_tag 'ids[]', issue.id, false, :id => nil %></td>
      <td class="subject"><%= link_to_issue(issue, :project => (@project != issue.project)) %></td>
    </tr>
  <% end %>
  </table>
<% end %>
<%= context_menu %>
<% end %>
</div>

<%= call_hook :view_versions_show_bottom, :version => @version %>

<% html_title @version.name %>

redmine/redmine-3.4.6/app/views/versions/status_by.js.erb
$('#status_by').html('<%= escape_javascript(render_issue_status_by(@version, params[:status_by])) %>');